version: '3.5'
services:
    spothood-db:
        container_name: spothood-db
        restart: always
        image: postgres:11
        ports:
            - 5431:5432
        env_file: dev-env
        networks:
            - spothood-network
        volumes:
            - spothood-pg-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "psql -U postgres", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

    spothood-api:
        container_name: spothood-api
        restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file: dev-env
        command: ["sh", "scripts/start.sh"]
        ports:
            - 8001:8001
        networks:
          - spothood-network
        volumes:
            - ./backend/spothood:/spothood/spothood
            - pip_cache:/usr/local/lib/python3.10/site-packages
        depends_on:
            spothood-db:
                condition: service_healthy
        healthcheck:
            test: "curl -f localhost:8001"
            interval: 5s
            timeout: 30s
            retries: 3

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=development
        healthcheck:
            test: "curl -f localhost:8080"
            interval: 5s
            timeout: 30s
            retries: 3

volumes:
    spothood-pg-data: {}
    pip_cache:

networks:
  spothood-network:
    external: true


